'use client'

// Per-product input-asset picker for the brief form. Lets the member reuse images from
// their library (uploads + seeds) or upload a new one from disk; selections serialize
// back to the comma-separated `input_assets` string the schema/from-form expect. Empty
// selection means the product is generated by the image model.
import { useId, useRef, useState } from 'react'
import Image from 'next/image'
import { Button } from '@/components/ui/button'
import {
  GalleryView,
  type GalleryColumn,
  type GallerySortOption,
} from '@/components/ui/gallery-view'
import { useToast } from '@/components/feedback/toast'
import { CheckIcon, ImageIcon, PlusIcon, SpinnerIcon, XIcon } from '@/components/icons'
import { formatBytes, formatDate } from '@/lib/format'
import type { AssetItem } from '@/features/brief/assets/use-asset-library'

function parseList(value: string): string[] {
  return value
    .split(/[\n,]/)
    .map((s) => s.trim())
    .filter(Boolean)
}

const ASSET_SORTS: GallerySortOption<AssetItem>[] = [
  { key: 'name', label: 'Name (A–Z)', compare: (a, b) => a.name.localeCompare(b.name) },
  {
    key: 'newest',
    label: 'Newest',
    compare: (a, b) => (b.createdAt ?? '').localeCompare(a.createdAt ?? ''),
  },
  { key: 'largest', label: 'Largest', compare: (a, b) => (b.size ?? 0) - (a.size ?? 0) },
]

interface AssetFieldProps {
  value: string
  onChange: (value: string) => void
  library: AssetItem[]
  onUploaded: () => void | Promise<void>
}

export function AssetField({ value, onChange, library, onUploaded }: AssetFieldProps) {
  const selected = parseList(value)
  const [open, setOpen] = useState(false)
  const [uploading, setUploading] = useState(false)
  const fileRef = useRef<HTMLInputElement>(null)
  const libraryId = useId()
  const toast = useToast()

  const commit = (names: string[]) => onChange(names.join(', '))
  const toggle = (name: string) =>
    commit(selected.includes(name) ? selected.filter((n) => n !== name) : [...selected, name])
  const urlFor = (name: string) => library.find((a) => a.name === name)?.url ?? null

  async function upload(file: File) {
    setUploading(true)
    try {
      const body = new FormData()
      body.append('file', file)
      const res = await fetch('/api/assets', { method: 'POST', body })
      const data = await res.json()
      if (!res.ok) {
        toast.error(data?.error ?? 'Upload failed')
        return
      }
      await onUploaded()
      if (!selected.includes(data.name)) commit([...selected, data.name])
      toast.success(`Uploaded ${data.name}`)
    } catch {
      toast.error('Upload failed')
    } finally {
      setUploading(false)
      if (fileRef.current) fileRef.current.value = ''
    }
  }

  const thumb = (asset: AssetItem) => (
    <span
      className="bg-muted relative block h-8 w-8 shrink-0 overflow-hidden"
      style={{ borderRadius: '2px' }}
    >
      {asset.url ? (
        <Image src={asset.url} alt="" fill sizes="32px" className="object-cover" />
      ) : (
        <span className="text-muted-foreground flex h-full items-center justify-center">
          <ImageIcon className="h-3.5 w-3.5" aria-hidden="true" />
        </span>
      )}
    </span>
  )

  const renderAssetCard = (asset: AssetItem) => {
    const isSelected = selected.includes(asset.name)
    return (
      <button
        type="button"
        onClick={() => toggle(asset.name)}
        aria-pressed={isSelected}
        aria-label={`${isSelected ? 'Deselect' : 'Select'} ${asset.name}`}
        className="border-border hover:border-brand-cyan block w-full overflow-hidden border focus-visible:ring-2 focus-visible:ring-offset-2"
        style={{
          borderRadius: 'var(--radius)',
          borderColor: isSelected ? 'var(--brand-cyan)' : undefined,
        }}
      >
        <span className="bg-muted relative block aspect-square w-full">
          {asset.url ? (
            <Image
              src={asset.url}
              alt={asset.name}
              fill
              sizes="(max-width: 640px) 33vw, 160px"
              className="object-cover"
            />
          ) : (
            <span className="text-muted-foreground flex h-full items-center justify-center">
              <ImageIcon className="h-6 w-6" aria-hidden="true" />
            </span>
          )}
          {isSelected && (
            <span className="bg-brand-cyan text-background absolute top-1 right-1 flex h-5 w-5 items-center justify-center rounded-full">
              <CheckIcon className="h-3.5 w-3.5" aria-hidden="true" />
            </span>
          )}
        </span>
        <span className="block truncate px-1 py-0.5 text-[10px]">{asset.name}</span>
      </button>
    )
  }

  const assetColumns: GalleryColumn<AssetItem>[] = [
    {
      key: 'check',
      header: '',
      width: '20px',
      align: 'center',
      cell: (a) =>
        selected.includes(a.name) ? (
          <CheckIcon className="text-brand-cyan h-4 w-4" aria-hidden="true" />
        ) : null,
    },
    { key: 'thumb', header: 'Image', width: '32px', cell: (a) => thumb(a) },
    {
      key: 'name',
      header: 'Name',
      width: 'minmax(0, 2fr)',
      cell: (a) => <span className="truncate">{a.name}</span>,
    },
    {
      key: 'size',
      header: 'Size',
      width: 'minmax(0, 1fr)',
      align: 'end',
      cell: (a) => (
        <span className="text-muted-foreground text-xs tabular-nums">
          {a.size != null ? formatBytes(a.size) : '—'}
        </span>
      ),
    },
    {
      key: 'date',
      header: 'Date',
      width: 'minmax(0, 1fr)',
      align: 'end',
      cell: (a) => (
        <span className="text-muted-foreground text-xs tabular-nums">
          {a.createdAt ? formatDate(a.createdAt) : '—'}
        </span>
      ),
    },
  ]

  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-wrap items-center justify-between gap-1">
        <span className="text-sm font-medium">Input assets</span>
        <span className="text-muted-foreground text-xs">
          Reuse these; leave empty to generate with the image model.
        </span>
      </div>

      <div aria-live="polite">
        {selected.length > 0 ? (
          <ul className="flex flex-wrap gap-2">
            {selected.map((name) => {
              const url = urlFor(name)
              return (
                <li
                  key={name}
                  className="border-border bg-card flex items-center gap-1.5 border py-1 pr-1.5 pl-1 text-xs"
                  style={{ borderRadius: 'var(--radius)' }}
                >
                  {url ? (
                    <span className="relative h-5 w-5 overflow-hidden rounded-[2px]">
                      <Image src={url} alt="" fill sizes="20px" className="object-cover" />
                    </span>
                  ) : (
                    <ImageIcon className="text-muted-foreground h-4 w-4" aria-hidden="true" />
                  )}
                  <span className="max-w-40 truncate">{name}</span>
                  <button
                    type="button"
                    onClick={() => toggle(name)}
                    aria-label={`Remove ${name}`}
                    className="hover:text-brand-hot-red focus-visible:ring-2 focus-visible:ring-offset-1"
                  >
                    <XIcon className="h-3.5 w-3.5" aria-hidden="true" />
                  </button>
                </li>
              )
            })}
          </ul>
        ) : (
          <p className="text-muted-foreground text-xs">
            No assets selected — this product is generated.
          </p>
        )}
      </div>

      <div className="flex flex-wrap gap-2">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => setOpen((o) => !o)}
          aria-expanded={open}
          aria-controls={libraryId}
        >
          <ImageIcon className="h-4 w-4" aria-hidden="true" />
          {open ? 'Hide library' : 'Choose from library'}
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => fileRef.current?.click()}
          disabled={uploading}
        >
          {uploading ? (
            <SpinnerIcon className="h-4 w-4 animate-spin" aria-hidden="true" />
          ) : (
            <PlusIcon className="h-4 w-4" aria-hidden="true" />
          )}
          Upload
        </Button>
        <input
          ref={fileRef}
          type="file"
          accept="image/png,image/jpeg,image/webp,image/gif"
          className="sr-only"
          aria-hidden="true"
          tabIndex={-1}
          onChange={(e) => {
            const file = e.target.files?.[0]
            if (file) void upload(file)
          }}
        />
      </div>

      <div id={libraryId}>
        {open &&
          (library.length === 0 ? (
            <p className="text-muted-foreground text-sm">
              Your library is empty — upload an image to reuse it here.
            </p>
          ) : (
            <GalleryView
              label="asset library"
              items={library}
              getKey={(a) => a.name}
              getSearchText={(a) => a.name}
              getRowLabel={(a) => `${selected.includes(a.name) ? 'Deselect' : 'Select'} ${a.name}`}
              onActivate={(a) => toggle(a.name)}
              isActive={(a) => selected.includes(a.name)}
              searchPlaceholder="Search library…"
              emptyMessage="No assets match your search."
              sorts={ASSET_SORTS}
              columns={assetColumns}
              renderGrid={(items) => (
                <ul className="grid grid-cols-3 gap-2 sm:grid-cols-4">
                  {items.map((asset) => (
                    <li key={asset.name}>{renderAssetCard(asset)}</li>
                  ))}
                </ul>
              )}
            />
          ))}
      </div>
    </div>
  )
}
